spring.application.name=StringMVC_TO_StringBoot
server.port=8080

# Base de donnees (identique au projet Spring MVC)
spring.datasource.url=jdbc:postgresql://localhost:5433/diti4_spring_mvc
spring.datasource.username=postgres
spring.datasource.password=gnay

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger UI : http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
